### ISSUE TITLE
[BUG] Some Direct link youtube videos fail to play

### ISSUE THREAD

**Issue by mchen804** [SushiBtw/discord-music-player#274] opened 2022-03-15 02:03 UTC
**Bug Description**
When providing a link to an age restricted video, even when ytdlCookie is provided the player will error with
`TypeError: Cannot read properties of undefined (reading 'secondaryResults'): There was an Unknown Error.
    at /Users/user/Documents/GitHub/discordBot/node_modules/discord-music-player/dist/managers/Queue.js:187:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`
    
The `Best` function doesn't handle an error from the `link` function
https://github.com/SushiBtw/discord-music-player/blob/master/src/utils/Utils.ts#L219

**Reproduction Steps**
1. Use ``play`` command with ``<some direct link to an age restricted video>``.
2. Error will be thrown and song will fail to play
3. Use ``play`` command with ``<name of age restricted video>`` and the song will play correctly

**Expected Result**
The video should play when given a direct link

**Attachments**

**Versioning:**
- OS: [OSX Monterey 12.2.1]
- Node Version [v17.7.1]
- Module Version [v8.3.1]

**Additional Comments**

**Comment by SushiBtw** [comment] 2022-04-07 05:26
Duplicate of new report #276 fixed by #275.

**Closed by SushiBtw** 2022-04-07 05:26 UTC
Labels: Bug
