### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EclipseGame18** [SushiBtw/discord-music-player#158] opened 2021-06-23 10:41 UTC
**Bug Description**
I use the play command and the bot joins and nothing happens

**Expected Result**
should play music 
**Versioning:**
 - OS: Heroku
 - NPM Version 12???
- Module Version: around new version

**Additional Comments**
I tried lots of different songs but the bot joins and nothing happens
e.g.
{prefix}play meme man or {prefix}play futurama theme full
>also sorry for finding another bug!

**Comment by lowikian** [comment] 2021-06-23 14:13
I have the same problem

**Comment by artificialai223** [comment] 2021-06-23 16:36
Bump, Same issue

**Comment by SushiBtw** [comment] 2021-06-23 16:41
Hey, seems that's a issue with YTDL, they are aware of it and they will be fixing it asap. I will update the module as soon it will be fixed.

**Comment by artificialai223** [comment] 2021-06-23 16:46
Ah alright, Good to know

**Comment by artificialai223** [comment] 2021-06-23 16:48
Could you add command handler integration? So people who have command handlers can add the commands to their dynamic commands such as help?

**Comment by artificialai223** [comment] 2021-06-23 16:50
Or is this the one where you specifically set your commands?

**Comment by SushiBtw** [comment] 2021-06-23 16:52
What do you mean, can you show me an example?

**Comment by artificialai223** [comment] 2021-06-23 16:54
Nevermind, I thought it was a different package but the error is for this

**Comment by artificialai223** [comment] 2021-06-23 16:54
Found a fix btw, https://github.com/fent/node-ytdl-core/issues/939#issuecomment-866241199

**Comment by artificialai223** [comment] 2021-06-23 16:55
One thing i would like though is better bass and better quality

**Comment by SushiBtw** [comment] 2021-06-23 16:59
> Found a fix btw, [fent/node-ytdl-core#939 (comment)](https://github.com/fent/node-ytdl-core/issues/939#issuecomment-866241199)

Thanks, I will implement that via creating a own package via forking that https://github.com/SushiBtw/node-ytdl-core, as that's on the MIT licence.

**Comment by SushiBtw** [comment] 2021-06-23 16:59
Fix incoming soon.

**Comment by SushiBtw** [comment] 2021-06-23 18:29
This issue was fixed in [v7.2.0](https://www.npmjs.com/package/discord-music-player/v/7.2.0) update that is live on NPM. Tell me if the issue was fixed 🎉

**Comment by ItsYourBoyNoah** [comment] 2021-06-23 18:57
> 
> 
> This issue was fixed in [v7.2.0](https://www.npmjs.com/package/discord-music-player/v/7.2.0) update that is live on NPM. Tell me if the issue was fixed 🎉

Hello, I updated the package, but when the bot joins there is no sound at all even though discord says it's speaking

**Comment by SushiBtw** [comment] 2021-06-23 18:59
Can you reinstall the package and take the installation steps again?

**Comment by ItsYourBoyNoah** [comment] 2021-06-23 19:01
> 
> 
> Can you reinstall the package and take the installation steps again?

I did still nothing

**Comment by SushiBtw** [comment] 2021-06-23 19:02
Can you open a new issue for it so we can move to another topic?
You can also join our Support Server - https://ssumbot.xyz/discord

**Comment by SushiBtw** [comment] 2021-06-23 19:36
@lowikian @EclipseGame18 @artificialai223 Tell me if it's fixed for you, if yes - we can close the issue :)

**Comment by lowikian** [comment] 2021-06-23 19:43
Everything works again

**Closed** 2021-06-24 05:40 UTC
Labels: Bug, Resolved, v7

**Comment by lemesherry** [comment] 2021-06-25 09:45
@SushiBtw  its a problem in ytdl-core and i have solution we just need to change a line of code in
node_modules\ytdl-core\lib\info.js
 I have complete code for that to i can fix my bot issues if i run it locally but the problem is i can't not deploy changes that i made inside ytdl to my heroku app ( any online hosting app ) i just need solution for that so if you have any solutions to deploy node_modules not to let heroku download node_modules itself, then i can give you that code and you can change that as i explained above.
 until ytdl-core dev realizes and fix this problem.
 its totally working fine ✅

**Comment by SushiBtw** [comment] 2021-06-25 09:49
I have made my own fork for node-ytdl and fixed it with v7.2.0 version. So it's fixed and live, just download the new update :)

**Comment by EclipseGame18** [comment] 2021-06-30 11:27
thanks for fixing it!

**Comment by lemesherry** [comment] 2021-07-01 01:19
> I have made my own fork for node-ytdl and fixed it with v7.2.0 version. So it's fixed and live, just download the new update :)

Thanks :heart:
